pipeline:
  build:
    image: golang:1.8
    environment:
    commands:
      - curl -L -o /tmp/hugo.tar.gz https://github.com/spf13/hugo/releases/download/v0.20.7/hugo_0.20.7_Linux-64bit.tar.gz
      - tar xvf /tmp/hugo.tar.gz -C /tmp/
      - mv /tmp/hugo /usr/bin/hugo
      - hugo -b http://blog.kube.camp
  
  docker-web:
    environment:
          - DOCKER_API_VERSION=1.24
    image: plugins/docker:1.12
    repo: quay.io/ipedrazas/kubecamp-blog
    tags: 
      - latest
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    registry: quay.io
    email: "info@info.com"
    debug: true
    dockerfile: ./client/Dockerfile
    secrets: [ docker_username, docker_password ]

  slack_success:
    image: plugins/slack
    channel: deploys
    username: kubot
    template: >
      {{ build.author }} finished building {{ repo.owner }}/{{ repo.name }} ({{ build.branch }})
    when:
      status: success
    secrets: [ slack_webhook]
