baseURL = "http://blog.kube.camp/"
languageCode = "en-us"
title = "blog"
theme = "hyde"

[params]
  themeColor = "theme-base-00"
  layoutReverse = true
  description = "About kubernetes and distributed systems"